#!/bin/sh -ex
w=exim4
docker build --tag $w .
docker kill $w || true
docker rm $w || true
docker run \
	--init \
	--publish 127.0.0.1:25:25 \
	--publish 587:587 \
	--detach \
	--name $w \
	--volume email:/mail \
	--volume exim4:/etc/exim-volume \
	--volume dovecot-sockets:/var/dovecot-sockets:ro \
	--volume letsencrypt-etc:/etc/letsencrypt:ro \
       	$w
docker logs --follow $w
