#!/bin/sh -ex
w=exim4
docker build --tag $w .
docker kill $w || true
docker rm $w || true
docker run \
	--init \
	--network proxy \
	--ip 192.168.42.3 \
	--detach \
	--name $w \
	--volume email:/mail \
	--volume dovecot-sockets:/var/dovecot-sockets:ro \
	--volume letsencrypt-etc:/etc/letsencrypt:ro \
       	$w
docker logs --follow $w
