#!/bin/sh -ex
cd $(dirname $0)
w=dovecot
docker build --tag $w . "$@"
docker kill $w || true
docker rm $w
docker run --init \
	--restart unless-stopped \
	--network proxy \
	--ip 192.168.42.1 \
	--detach \
	--name $w \
	--volume email:/mail \
	--volume dovecot-sockets:/var/sockets \
       	$w
#docker network connect --ip 192.168.42.1 proxy $w
docker logs --follow $w
