#!/bin/sh -ex
w=dovecot
docker build --tag $w .
docker kill $w
docker rm $w
docker run --init \
	--network proxy \
	--ip 192.168.42.1 \
	--detach \
	--name $w \
       	$w
#docker network connect --ip 192.168.42.1 proxy $w
docker logs --follow $w
