#!/bin/sh -e
cd $(dirname "$0")
w=matrix-synapse
docker build "$@" --tag matrix-synapse . # --no-cache
docker stop matrix-synapse || true
docker rm matrix-synapse || true
restart="--restart unless-stopped"
docker run \
	--cap-drop=all \
	$restart \
	--name matrix-synapse \
	--detach \
	--network postgresql \
	--mount source=matrix-media,destination=/var/lib/matrix-synapse/media \
	--init \
	matrix-synapse
docker network connect proxy matrix-synapse
docker logs --follow matrix-synapse
