#!/bin/sh -ex
w=postgresql
docker build --tag postgresql .
docker stop postgresql || true
docker rm postgresql || true
docker run \
	--init \
	--detach \
	--name postgresql \
	--mount source=postgresql12-db,destination=/var/lib/postgresql \
	--restart unless-stopped \
	--network postgresql \
	--cap-drop=all \
	postgresql
docker logs --follow postgresql
