# vim:ft=yaml
# https://github.com/matrix-org/synapse/issues/2438

uploads_path: /var/lib/matrix-synapse/uploads
turn_user_lifetime: 1d
turn_allow_guest: False
suppress_key_server_warning: True

## Server ##

# List of ports that Synapse should listen on, their purpose and their
# configuration.
listeners:
  # Main HTTPS listener
  # For when matrix traffic passes through loadbalancer that unwraps TLS.
  -
    port: 8448
    bind_address: ''
    type: http
    tls: false
    x_forwarded: true

    # List of HTTP resources to serve on this listener.
    resources:
      - names: [federation]  # Federation APIs
        compress: false

  # Unsecure HTTP listener,
  # For when matrix traffic passes through loadbalancer that unwraps TLS.
  - port: 8008
    tls: false
    bind_address: ''
    type: http

    # Use the X-Forwarded-For (XFF) header as the client IP and not the
    # actual client IP.
    x_forwarded: true

    resources:
      - names: [client]
        compress: true
