# vim:ft=yaml

# Don't bind to the https port
no_tls: True

## Server ##

# When running as a daemon, the file to store the pid in
pid_file: /run/homeserver.pid

# List of ports that Synapse should listen on, their purpose and their
# configuration.
listeners:
  # Main HTTPS listener
  # For when matrix traffic is sent directly to synapse.
  -
    # The port to listen for HTTPS requests on.
    port: 8448

    # Local addresses to listen on.
    # This will listen on all IPv4 addresses by default.
    bind_addresses:
      - '0.0.0.0'
      # Uncomment to listen on all IPv6 interfaces
      # N.B: On at least Linux this will also listen on all IPv4
      # addresses, so you will need to comment out the line above.
      # - '::'

    # This is a 'http' listener, allows us to specify 'resources'.
    type: http

    tls: true

    # Use the X-Forwarded-For (XFF) header as the client IP and not the
    # actual client IP.
    x_forwarded: false

    # List of HTTP resources to serve on this listener.
    resources:
      -
        # List of resources to host on this listener.
        names:
          - client     # The client-server APIs, both v1 and v2
#          - webclient  # The bundled webclient.
#
#        # Should synapse compress HTTP responses to clients that support it?
#        # This should be disabled if running synapse behind a load balancer
#        # that can do automatic compression.
        compress: true
#
      - names: [federation]  # Federation APIs
        compress: false

  # Unsecure HTTP listener,
  # For when matrix traffic passes through loadbalancer that unwraps TLS.
  - port: 8008
    tls: false
    bind_addresses: ['0.0.0.0']
    type: http

    x_forwarded: true

    resources:
      - names: [client, webclient]
        compress: true

## Signing Keys ##
# Path to the signing key to sign messages with
signing_key_path: "/etc/matrix-synapse/signing.key"

## Registration ##
# Enable registration for new users.
enable_registration: False

## Turn ##
# How long generated TURN credentials last
turn_user_lifetime: "1h"
