# Database configuration
database:
  # The database engine name
  name: "psycopg2"
  # Arguments to pass to the engine
  args:
# https://github.com/matrix-org/synapse/blob/master/docs/postgres.rst
    user: matrix
    database: synapse
    host: postgres
    cp_min: 3
    cp_max: 10
# do not add anything after this line!
