#!/bin/sh -ex
docker build --tag coturn "$@" . # --no-cache
docker stop coturn
docker rm coturn
docker run \
	--restart unless-stopped \
	--detach \
	--publish 3478:3478/udp \
	--publish  3478:3478 \
	--publish 49152-49352/udp \
	--publish 49152-49352 \
	--name coturn \
	--cap-drop=all \
	coturn
docker logs --follow coturn
