#!/bin/sh -xe
. ./secrets.sh
# https://vsupalov.com/docker-build-time-env-values/
docker build --build-arg DBPASSWD=${DBPASSWD?} --tag mozillasync "$@" . # --no-cache
docker stop mozillasync || true
docker rm mozillasync || true
docker run --init \
	--detach \
	--network postgresql \
	--name mozillasync \
	--cap-drop=all \
	--restart unless-stopped \
	mozillasync # -xc "sleep 23423d"
docker network connect proxy mozillasync
docker logs --follow mozillasync
exit 0
