#!/bin/sh -xe
docker build --tag etesync "$@" . # --no-cache
docker stop etesync || true
docker rm etesync || true
docker volume inspect etesync-v2-db > /dev/null 2>&1 || docker volume create etesync-v2-db
docker run --init \
	--detach \
	--network proxy \
	--name etesync \
	--cap-drop=all \
	--mount type=volume,source=etesync-v2-db,destination=/db \
	--restart unless-stopped \
	etesync
docker logs --follow etesync
exit 0
