#!/bin/sh -ex
w=etesync
docker build --tag $w .
docker kill $w || true
docker rm $w || true
docker run --init \
	--detach \
	--network proxy \
	--name $w \
	--cap-drop=all \
	--mount type=volume,source=etesync-db,destination=/db \
       	$w
#docker network connect --ip 192.168.42.1 proxy $w
docker logs --follow $w
exit 0

	--restart unless-stopped \
