#!/bin/sh
umask 077
cmd="/usr/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/"
$cmd --generate-keys
case "$*" in
"")
	case $? in
	0)
		exec $cmd
		;;
	*)
		exit $?
		;;
	esac
	;;
*)
	exec "$@"
	;;
esac
