#!/bin/sh -ex
# https://github.com/nextcloud/docker
. ./passwords
w=nextcloud
docker kill $w || true
docker rm $w || true
docker run \
	--detach \
	--volume nextcloud_app:/var/www/html \
	--volume nextcloud_apps:/var/www/html/custom_apps \
	--volume nextcloud_config:/var/www/html/config \
	--volume nextcloud_data:/var/www/html/data \
	--network mariadb \
	--name $w \
	--env MYSQL_DATABASE=nextcloud \
	--env MYSQL_USER=nextcloud \
	--env MYSQL_PASSWORD="${MYSQL_PASSWORD?}" \
	--env MYSQL_HOST=mariadb \
	--env NEXTCLOUD_ADMIN_USER=slpadmin \
	--env NEXTCLOUD_ADMIN_PASSWORD="${NEXTCLOUD_ADMIN_PASSWORD?}" \
	--restart unless-stopped \
	$w

docker network connect proxy $w
docker logs --follow $w
