#!/bin/sh -ex
# https://github.com/nextcloud/docker
. ./passwords
w=nextcloud
docker stop $w || true
docker rm $w || true
version=15 # only increase versions one at a time
docker run \
	--detach \
	--volume nextcloud_app2:/var/www/html \
	--volume nextcloud_apps2:/var/www/html/custom_apps \
	--volume nextcloud_config2:/var/www/html/config \
	--volume nextcloud_data2:/var/www/html/data \
	--network postgresql \
	--name $w \
	--env POSTGRES_DB=nextcloud \
	--env POSTGRES_USER=nextcloud \
	--env POSTGRES_PASSWORD="${POSTGRES_PASSWORD=?}" \
	--env POSTGRES_HOST=postgresql \
	--env NEXTCLOUD_ADMIN_USER=slpadmin \
	--env NEXTCLOUD_ADMIN_PASSWORD="${NEXTCLOUD_ADMIN_PASSWORD?}" \
	--restart unless-stopped \
	$w:$version

docker network connect proxy $w
docker logs --follow $w
