#!/bin/sh -xe
docker build --tag syncserver "$@" . # --no-cache
docker stop syncserver || true
docker rm syncserver || true
docker run --init \
	--detach \
	--network proxy \
	--name syncserver \
	--cap-drop=all \
	--restart unless-stopped \
	syncserver # -xc "sleep 23423d"
#docker network connect --ip 192.168.42.1 proxy etesync
docker logs --follow syncserver
exit 0
	--mount type=volume,source=etesync-db,destination=/db \
