#!/bin/sh -xe
cd $(dirname "$0")
n=proxy
docker build --tag myproxy .
docker stop $n
docker rm proxy
docker run --detach \
	--network proxy \
	--ip 192.168.42.2 \
	--publish 80:80 \
	--publish 443:443 \
	--publish 143:143 \
	--volume letsencrypt-etc:/etc/letsencrypt:ro \
	--volume letsencrypt-run:/run/letsencrypt:ro \
	--name $n \
	--restart unless-stopped \
	myproxy \
	"$@"
docker logs --follow proxy
