#!/bin/sh
# https://hub.docker.com/_/mariadb/
exec docker run \
	--detach \
	--name mariadb \
	--env MYSQL_ROOT_PASSWORD="${1?}" \
	--env MYSQL_DATABASE=nextcloud \
	--env MYSQL_USER=nextcloud \
	--env MYSQL_PASSWORD="${2?}" \
	--network mariadb \
	--restart unless-stopped \
	mariadb:latest
	
